function(add_custom_test target_name)
add_executable(${target_name}_test ${target_name}.cpp)
custom_configure_sycl(${target_name}_test)
target_link_libraries(${target_name}_test PRIVATE ${PROJECT_NAME})
endfunction()
add_subdirectory(buffer)
add_subdirectory(epidemiological)
add_subdirectory(graph)
add_subdirectory(gt)
add_subdirectory(simulation)
