include(CTest)
function(add_custom_test source_name)
add_executable(${source_name} ${source_name}.cpp)
target_link_libraries(${source_name} PUBLIC SIR_SBM_core ${${PROJECT_NAME}_EXTERNAL_TEST_LIBRARIES})
add_test(NAME ${source_name} COMMAND ${source_name})
custom_configure_sycl(${source_name})
endfunction()
if(${SIR_SBM_USE_GPU})
message(STATUS "Building tests targeted for GPU")
else()
message(STATUS "Building tests targeted for CPU")
endif()
add_subdirectory(simulation)
add_subdirectory(gt)

add_custom_test(sycl_ls)
# add_subdirectory(graph)
# add_subdirectory(epidemiological)
