function(custom_configure_sycl target_name)
set(${PROJECT_NAME}_SYCL_TARGETS "")
if(${SBM_USE_GPU})
set(${PROJECT_NAME}_SYCL_TARGETS "nvptx64-nvidia-cuda")
endif()
if(${SBM_USE_CPU})
set(${PROJECT_NAME}_SYCL_TARGETS "${${PROJECT_NAME}_SYCL_TARGETS},native_cpu")
endif()
target_compile_options(${target_name} PUBLIC "-fsycl")
target_link_options(${target_name} PUBLIC "-fsycl")
target_include_directories(${target_name} PUBLIC ${SYCL_INCLUDE_DIR})
target_compile_options(${target_name} PUBLIC "-fsycl-targets=${${PROJECT_NAME}_SYCL_TARGETS}")
target_link_options(${target_name} PUBLIC "-fsycl-targets=${${PROJECT_NAME}_SYCL_TARGETS}")
endfunction()