function(custom_configure_sycl target_name)
set(${PROJECT_NAME}_SYCL_TARGETS "")
if(${SIR_SBM_USE_GPU})
set(${PROJECT_NAME}_SYCL_TARGETS "${${PROJECT_NAME}_SYCL_TARGETS};")
endif()
if(${SIR_SBM_USE_CPU})
set(${PROJECT_NAME}_SYCL_TARGETS "${${PROJECT_NAME}_SYCL_TARGETS};x86_64")
endif()
target_compile_options(${target_name} PUBLIC "-fsycl")
target_link_options(${target_name} PUBLIC "-fsycl")
target_include_directories(${target_name} PUBLIC ${SYCL_INCLUDE_DIR})
target_compile_options(${target_name} PUBLIC "-fsycl-targets=${${PROJECT_NAME}_SYCL_TARGETS}")
target_link_options(${target_name} PUBLIC "-fsycl-targets=${${PROJECT_NAME}_SYCL_TARGETS}")
endfunction()