function(custom_configure_sycl target_name)
target_compile_options(${target_name} PUBLIC "-fsycl")
if(${SIR_SBM_USE_GPU})
target_compile_definitions(${target_name} PUBLIC SIR_SBM_USE_GPU)
target_compile_options(${target_name} PUBLIC "-fsycl-targets=nvptx64-nvidia-cuda")
target_link_options(${target_name} PUBLIC "-fsycl-targets=nvptx64-nvidia-cuda")
else()
target_compile_definitions(${target_name} PUBLIC SIR_SBM_USE_CPU)
target_compile_options(${target_name} PUBLIC "-fsycl-targets=spir64_x86_64")
target_link_options(${target_name} PUBLIC "-fsycl-targets=spir64_x86_64")
endif()
endfunction()