function(add_sycl_executable source_file)
    add_executable(${source_file} "${source_file}.cpp")
    target_link_libraries(${source_file} PUBLIC Simulation Static_RNG::Static_RNG cppitertools)
    if(${ENABLE_TBB})
    target_link_libraries(${source_file} PUBLIC tbb)
    endif()
    target_compile_options(${source_file} PRIVATE ${SYCL_CUSTOM_FLAGS})
    target_compile_options(${source_file} PRIVATE ${DEFAULT_WARNING_FLAGS})
    target_include_directories(${source_file} PUBLIC ${SYCL_GRAPH_INCLUDE_DIR})
    # target_link_options(${source_file} PRIVATE -static-libgcc -static-libstdc++)
endfunction()

function(add_sycl_executable_nodep source_file)
    add_executable(${source_file} "${source_file}.cpp")
    target_compile_options(${source_file} PRIVATE ${SYCL_CUSTOM_FLAGS})
    target_compile_options(${source_file} PRIVATE ${DEFAULT_WARNING_FLAGS})
    target_include_directories(${source_file} PUBLIC ${SYCL_GRAPH_INCLUDE_DIR})
endfunction()

function(add_regression_executable source_file)
    add_executable(${source_file} "${source_file}.cpp")
    target_link_libraries(${source_file} PUBLIC Static_RNG::Static_RNG Eigen3::Eigen ortools::ortools Regression)
    if(${ENABLE_TBB})
        target_link_libraries(${source_file} PUBLIC tbb)
    endif()
    target_include_directories(${source_file} PUBLIC ${SYCL_GRAPH_INCLUDE_DIR})
endfunction()
