function(add_custom_binder source_file)
    pybind11_add_module(${source_file} "${source_file}.cpp")
    # target_link_libraries(${source_file} PUBLIC SBM_Simulation)
    target_compile_options(${source_file} PRIVATE ${DEFAULT_WARNING_FLAGS})
    target_compile_options(${source_file} PUBLIC ${SYCL_CUSTOM_FLAGS} -fsycl -fPIC ${SBM_SIMULATION_DEFAULT_FLAGS})
    target_include_directories(${source_file} PUBLIC $<BUILD_INTERFACE:${SBM_SIMULATION_INCLUDE_DIR}> $<INSTALL_INTERFACE:include>)
    target_link_options(${source_file} PUBLIC ${SYCL_CUSTOM_FLAGS} ${SBM_SIMULATION_DEFAULT_FLAGS} -fPIC)
endfunction()




function(add_custom_library source_file)
    add_library(${source_file} STATIC "${source_file}.cpp")
    target_link_libraries(${source_file} PUBLIC -ldl -lpq Static_RNG::Static_RNG)
    if(${ENABLE_TBB})
        target_link_libraries(${source_file} PUBLIC TBB::tbb)
    endif()
    target_compile_options(${source_file} PUBLIC -fsycl ${SYCL_CUSTOM_FLAGS})
    target_compile_options(${source_file} PUBLIC ${DEFAULT_WARNING_FLAGS} ${SBM_SIMULATION_DEFAULT_FLAGS})
    target_include_directories(${source_file} PUBLIC $<BUILD_INTERFACE:${SBM_SIMULATION_INCLUDE_DIR}> $<INSTALL_INTERFACE:include>)
    target_link_options(${source_file} PUBLIC ${SYCL_CUSTOM_FLAGS} ${SBM_SIMULATION_DEFAULT_FLAGS})
    if (${ENABLE_CLANG_TIDY})
    set_target_properties(${source_file} PROPERTIES CXX_CLANG_TIDY "${CLANG_TIDY_COMMAND}")
    endif()
endfunction()
