include(${CMAKE_CURRENT_LIST_DIR}/configure_sycl.cmake)
if(NOT DEFINED custom_test_targets)
set(custom_test_targets "")
endif()
macro(add_custom_test target_name libraries)
add_executable(${target_name}_test ${target_name}.cpp)
custom_configure_sycl(${target_name}_test)
target_link_libraries(${target_name}_test PRIVATE ${libraries})
set(custom_test_targets ${custom_test_targets} ${target_name}_test PARENT_SCOPE)
endmacro()
