
function(default_configure_target target_name)
    target_compile_options(${target_name} PUBLIC -fsycl ${SYCL_CUSTOM_FLAGS} -Wno-deprecated-declarations)
    target_link_options(${target_name} PUBLIC -fsycl -fsycl-targets=${${PROJECT_NAME}_SYCL_TARGETS} -Wno-deprecated-declarations)
    target_include_directories(${target_name} PUBLIC $<BUILD_INTERFACE:${${PROJECT_NAME}_INCLUDE_DIR}> $<INSTALL_INTERFACE:include>)
    target_include_directories(${target_name} PUBLIC $<BUILD_INTERFACE:${SYCL_INCLUDE_DIR}>)
    if (${ENABLE_CLANG_TIDY})
    set_target_properties(${target_name} PROPERTIES CXX_CLANG_TIDY "${CLANG_TIDY_COMMAND}")
    endif()
endfunction()

function(link_default_libraries target_name)
target_link_libraries(${target_name} PRIVATE ${${PROJECT_NAME}_EXTERNAL_PACKAGES})
endfunction()

function(add_binder source_file)
    pybind11_add_module(${source_file} "${source_file}.cpp")
    default_configure_target(${source_file})
endfunction()

function(add_default_library source_file)
    add_library(${source_file} "${source_file}.cpp")
    default_configure_target(${source_file})
endfunction()


function(add_default_executable source_file)
    add_executable(${source_file} "${source_file}.cpp")
    default_configure_target(${source_file})
    link_default_libraries(${source_file})
    target_link_libraries(${source_file} PRIVATE ${PROJECT_NAME})
    # target_include_directories(${source_file} PUBLIC $<BUILD_INTERFACE:${${PROJECT_NAME}_INCLUDE_DIR}> $<INSTALL_INTERFACE:include>)
    # target_link_options(${source_file} PRIVATE -fsycl ${SYCL_CUSTOM_FLAGS} -Wno-deprecated-declarations)
    # target_compile_options(${source_file} PRIVATE -fsycl ${SYCL_CUSTOM_FLAGS} -Wno-deprecated-declarations)
endfunction()
