include(FindPkgConfig)
include(FindOpenMP)
# find_package(Boost REQUIRED COMPONENTS python)
pkg_check_modules(graphtool graph-tool-py${Python3_VERSION_MAJOR}.${Python3_VERSION_MINOR})
function(graphtool_configure target)
target_include_directories(${target} PUBLIC ${graphtool_INCLUDE_DIRS})
target_link_libraries(${target} PUBLIC OpenMP::OpenMP_CXX ${graphtool_LIBRARIES})
target_link_directories(${target} PUBLIC ${graphtool_LIBRARY_DIRS})
endfunction()