if(${SYCL_GRAPH_USE_INTEL})
    find_package(IntelDPCPP REQUIRED HINTS "/opt/intel/oneapi/compiler/latest/linux/IntelDPCPP")
    set(TBB_DIR "/opt/intel/oneapi/tbb/latest/lib/cmake/tbb/")
    set(SYCL_GRAPH_USE_SYCL ON)
endif()

if(${SYCL_GRAPH_USE_ONEAPI})
    find_package(TBB CONFIG REQUIRED)
    find_package(oneDPL CONFIG REQUIRED)
    set(ONEAPI_LIBRARIES TBB::tbb oneDPL)
endif()